rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - 1.9.3
  - jruby-19mode
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
before_install:
  - gem update --system
  - gem update bundler
install: "bundle install"
