rvm:
  - 2.4.0
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - jruby-19mode
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
before_install:
  - gem update --system
  - gem update bundler
install: "bundle install"

matrix:
  exclude:
    # Rails 5 requires Ruby >= 2.2.2
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails_5.1.gemfile
